server:
  port: 8080
  servlet:
    context-path: /api/creepy


spring:
  jpa:
    database: MYSQL
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/creepy?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: docker