server:
  port: 8081

spring:
  profiles:
    active: oauth-security

  jpa:
    database: MYSQL
    show-sql: true

  datasource:
    url: jdbc:mysql://localhost:3306/auth_creepy?useTimezone=true&serverTimezone=UTC&createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: docker

